Repository programmersarena/OSI-Visualizer, pull requests merged in 2025-03, with the labels that each got.

#20 [BugFix] fixed typescript errors
  osi-frontend/src/app/components/DnsLookup.tsx
  osi-frontend/src/app/components/OsiVisualization.tsx
  osi-frontend/src/app/page.tsx
Labels: bug

#25 added dockerfile
  osi-backend/Dockerfile.backend
Labels: devops

#40 add session layer
  osi-frontend/package-lock.json
  osi-frontend/package.json
  osi-frontend/src/app/components/Osi_Components/OsiVisualization.tsx
  osi-frontend/src/app/components/Session_Layer/Session.tsx
Labels: development
